# Generated by Django 4.2.3 on 2023-08-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_alter_mailingsettings_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglog',
            name='mailing_service_response',
            field=models.TextField(blank=True, null=True, verbose_name='Результат'),
        ),
    ]
